In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv(r"C:\Users\hp\Downloads\clinical_trial_data\ctg-studies.csv")

In [6]:
df.head()

,NCT_Number,Study_Title,Study_Status,Conditions,Interventions,Sponsor,Collaborators,Sex,Age,Phases,Enrollment,Funder_Type,Study_Type,Study_Design,Start_Date,Primary_Completion_Date,Completion_Date,First_Posted,Last_Update_Posted,Locations
0,NCT07290231,Effects of Core Strengthening Exercises With D...,RECRUITING,Diabetes Type II,OTHER: Core Strengthening with Diaphragmatic B...,Foundation University Islamabad,NaN,ALL,ADULT,NaN,56.0,OTHER,INTERVENTIONAL,Allocation: RANDOMIZED | Intervention Model: P...,06-08-2025,03-01-2026,10-02-2026,18-12-2025,18-12-2025,Foundation University College of Physical Ther...
1,NCT02074540,The Influence of Health Beliefs and Uncertaint...,UNKNOWN,Diabetes Type II,OTHER: Questionnaire,Hillel Yaffe Medical Center,NaN,ALL,"ADULT, OLDER_ADULT",NaN,100.0,OTHER_GOV,OBSERVATIONAL,Observational Model: CASE_ONLY | Time Perspect...,2014-04,2014-08,2014-12,28-02-2014,28-02-2014,NaN
2,NCT02326129,Novel Biomarker for Development of T2D,COMPLETED,Diabetes Type II,NaN,Duke University,Children's Miracle Network|National Institute ...,ALL,"CHILD, ADULT",NaN,202.0,OTHER,OBSERVATIONAL,Observational Model: CASE_CONTROL | Time Persp...,2015-02,05-04-2023,05-04-2023,25-12-2014,07-08-2023,"Pennington Biomedical Research center, Baton R..."
3,NCT06864546,A Participatory Approach to Support Glucose To...,RECRUITING,"Type 2 Diabetes Mellitus, Non Insulin Dependent",BEHAVIORAL: Physical activity intervention,Enea Parimbelli,Istituti Clinici Scientifici Maugeri SpA|Unive...,ALL,"ADULT, OLDER_ADULT",NaN,20.0,OTHER,INTERVENTIONAL,Allocation: NA | Intervention Model: SINGLE_GR...,2025-05,2025-12,15-01-2026,07-03-2025,30-04-2025,"Istituti Clinici Scientifici Maugeri di Pavia,..."
4,NCT04501341,BM-MNC and UCMSC for Type 2 Diabetes Mellitus ...,UNKNOWN,T2D,"BIOLOGICAL: Bone-marrow aspiration, Intra-panc...",Indonesia University,Dr Cipto Mangunkusumo General Hospital,ALL,"ADULT, OLDER_ADULT",PHASE1|PHASE2,15.0,OTHER,INTERVENTIONAL,Allocation: NON_RANDOMIZED | Intervention Mode...,14-03-2016,01-12-2021,01-12-2021,06-08-2020,06-08-2020,"Faculty of Medicine, Universitas Indonesia, Ja..."

In [8]:
df.shape

(500, 20)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NCT_Number               500 non-null    str
 1   Study_Title              500 non-null    str
 2   Study_Status             500 non-null    str
 3   Conditions               500 non-null    str
 4   Interventions            472 non-null    str
 5   Sponsor                  500 non-null    str
 6   Collaborators            137 non-null    str
 7   Sex                      500 non-null    str
 8   Age                      500 non-null    str
 9   Phases                   250 non-null    str
 10  Enrollment               497 non-null    float64
 11  Funder_Type              500 non-null    str
 12  Study_Type               500 non-null    str
 13  Study_Design             499 non-null    str
 14  Start_Date               500 non-null    str
 15  Primary_Completion_Date  481 non-null    str
 16  Completion_Date          484 non-null    str
 17  First_Posted             500 non-null    str
 18  Last_Update_Posted       500 non-null    str
 19  Locations                448 non-null    str
dtypes: float64(1), str(19)
memory usage: 78.3 KB

**Data Quality Assessment**

In [10]:
missing = pd.DataFrame({
    'Missing_Count': df.isnull().sum(),
    'Missing_Persent': round((df.isnull().sum()/len(df))*100,2)
})

missing.sort_values(
    'Missing_Persent',
    ascending = False
)

                         Missing_Count  Missing_Persent
Collaborators                      363             72.6
Phases                             250             50.0
Locations                           52             10.4
Interventions                       28              5.6
Primary_Completion_Date             19              3.8
Completion_Date                     16              3.2
Enrollment                           3              0.6
Study_Design                         1              0.2
Conditions                           0              0.0
Study_Status                         0              0.0
Study_Title                          0              0.0
NCT_Number                           0              0.0
Funder_Type                          0              0.0
Age                                  0              0.0
Sponsor                              0              0.0
Sex                                  0              0.0
Start_Date                           0              0.0
Study_Type                           0              0.0
First_Posted                         0              0.0
Last_Update_Posted                   0              0.0

In [13]:
date_cols = [
    'Start_Date',
    'Primary_Completion_Date',
    'Completion_Date',
    'First_Posted',
    'Last_Update_Posted'
]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NCT_Number               500 non-null    str
 1   Study_Title              500 non-null    str
 2   Study_Status             500 non-null    str
 3   Conditions               500 non-null    str
 4   Interventions            472 non-null    str
 5   Sponsor                  500 non-null    str
 6   Collaborators            137 non-null    str
 7   Sex                      500 non-null    str
 8   Age                      500 non-null    str
 9   Phases                   250 non-null    str
 10  Enrollment               497 non-null    float64
 11  Funder_Type              500 non-null    str
 12  Study_Type               500 non-null    str
 13  Study_Design             499 non-null    str
 14  Start_Date               148 non-null    datetime64[us]
 15  Primary_Completion_Date  97 non-null     datetime64[us]
 16  Completion_Date          87 non-null     datetime64[us]
 17  First_Posted             500 non-null    datetime64[us]
 18  Last_Update_Posted       500 non-null    datetime64[us]
 19  Locations                448 non-null    str
dtypes: datetime64[us](5), float64(1), str(14)
memory usage: 78.3 KB

In [15]:
df['Trial_Duration_Days'] = (
    df['Completion_Date'] -
    df['Start_Date']
).dt.days

In [17]:
df['Trial_Duration_Days'].describe()

count      49.000000
mean      444.163265
std       414.684084
min      -179.000000
25%       156.000000
50%       365.000000
75%       724.000000
max      2184.000000
Name: Trial_Duration_Days, dtype: float64

In [18]:
df[df['Trial_Duration_Days'] < 0][[
    'NCT_Number',
    'Study_Title',
    'Start_Date',
    'Completion_Date',
    'Trial_Duration_Days'
]]

,NCT_Number,Study_Title,Start_Date,Completion_Date,Trial_Duration_Days
221,NCT05741437,A Clinical Trial to Compare and Evaluate the S...,2023-11-04,2023-05-09,-179.0

In [19]:
df.loc[
    df['Trial_Duration_Days'] < 0,
    'Trial_Duration_Days'
] = pd.NA

In [21]:
df['Trial_Duration_Days'].describe()

count      48.000000
mean      457.145833
std       408.885251
min         1.000000
25%       178.500000
50%       365.500000
75%       724.250000
max      2184.000000
Name: Trial_Duration_Days, dtype: float64

In [28]:
def enrollment_category(x):

    if pd.isna(x):
        return "Unknown"
    elif x < 100:
        return "Small"   
    elif x < 500:
        return "Medium"  
    else:
        return "Large"  
df['Enrollment_Category'] = df['Enrollment'].apply(enrollment_category)

In [29]:
df['Enrollment_Category'].value_counts()

Enrollment_Category
Small      259
Medium     180
Large       58
Unknown      3
Name: count, dtype: int64

In [30]:
df['Age_Group_Count'] = (
    df['Age']
    .fillna('')
    .str.split(',')
    .str.len()
)

In [31]:
df[['Age','Age_Group_Count']].head()

                  Age  Age_Group_Count
0               ADULT                1
1  ADULT, OLDER_ADULT                2
2        CHILD, ADULT                2
3  ADULT, OLDER_ADULT                2
4  ADULT, OLDER_ADULT                2

In [32]:
df.to_csv(
    "Clinical_trial_cleaned.csv",
    index=False
)

print("Clean datset saved succesfully!")

Clean datset saved succesfully!

In [2]:
import os

print(os.listdir())

['1 B-Ed 06082025-pages-deleted (2).pdf', '10th or equivalent examination Proof.pdf', '10_PV_Case_Narratives (1).docx', '10_PV_Case_Narratives.docx', '11zon_JPEG-to-PDF.pdf', '1515_imresizer.jpg', '1965041823038_1.pdf', '241620089894_1734514445.pdf', '2675000523206111995_copy.pdf', '36683-C68925 (1).xlsx', '36683-C68925.pdf', '36683-C68925.xlsx', '36683-C689251.pdf', '45bd6a03-bf76-40e9-b0ad-bfe774012e9b.jpeg', '640441 (1).pdf', '640441.pdf', '7cd6f7bb-9d56-49dc-9400-78a7c0216e74.jpeg', '8. Ms. Jijau Khandale M (2).pdf', 'A project Report jvv.pdf', 'ADHARCARDSMK.pdf', 'ADI.jpeg', 'ADI12 (1).jpeg', 'ADI12.jpeg', 'ADI1234.jpeg', 'AdmissionCertificate (1).pdf', 'AdmissionCertificate (2).pdf', 'AdmissionCertificate.pdf', 'Adobe Photoshop Installer.exe', 'ADR.xlsx', 'ADR_dataset.xlsx', 'Adverse_event_reporting_dataset.xlsx', 'AFCAT Model Question Paper-I.pdf', 'aksing.jpeg', 'Amazon-Sales-Data-Analysis', 'Amazon.csv', 'AMAZON_PROJECT.sql', 'Amazon_Sales_Analytics_Report.docx', 'Amazon_Sales_Dashboard.pbix', 'amazon_sales_dashbpard.pbix', 'amazon_sales_data 2025.csv', 'amazon_sales_final.csv', 'amk BPEd.pdf', 'AMK NEW PHOTO.jpg', 'AMK NEW PHOTO_25.jpg', 'AMK NEW PHOTO_enhanced.jpg', 'AMK1-removebg-preview.png', 'AMK1.jpeg', 'AMK12.jpeg', 'AMK123 (1).jpg', 'AMK123 (2).jpg', 'AMK123 (3).jpg', 'AMK123.jpg', 'AMKPHOTO30.jpg', 'AMKSIGN-removebg-previe.jpeg', 'AMKSIGN-removebg-preview.png', 'amksign.jpeg', 'amksign171.jpeg', 'amksing.jpeg', 'Aniket Adhar Card.pdf', 'aniket cast .pdf', 'aniket caste certificate.pdf', 'Aniket Khandale-Resume.pdf', 'ANIKET PHOTO-removebg-preview.jpg', 'aniket photo.pdf', 'ANIKET PHOTO.png', 'Aniket Signature.pdf', 'aniketk signature.pdf', 'aniketsccboard.pdf', 'AnyDesk.exe', 'APPAR ID SMK 0008.pdf', 'application (1).pdf', 'application (2).pdf', 'application (3).pdf', 'application (4).pdf', 'Application for medical coder.pdf', 'Application gd ssc sagar.pdf', 'Application-Form.docx', 'application.pdf', 'ApplicationForm-20320022 (1).pdf', 'ApplicationForm-20320022.pdf', 'AppSuite-PDF.msi', 'archive (1).zip', 'archive (2)', 'archive (2).zip', 'archive (3)', 'archive (3).zip', 'archive (4).zip', 'archive.zip', 'B12.jpeg', 'B123.jpeg', 'balu ssc.pdf', 'Basic management resume.docx', 'Basic-CV-Template.docx', 'bce5a221eef745f580d2d43b48d8c33c.jpg', 'BEd fee recipit .jpg', 'BEd formate  12345.pdf', 'BEd formate new smk   1234567.pdf', 'BEd formate new smk (1).pdf', 'BEd formate new smk.pdf', 'BEd formate page (1).pdf', 'BEd formate page 123 (1).pdf', 'BEd formate page 123.pdf', 'BEd formate page 1234 (1).pdf', 'BEd formate page 1234.pdf', 'BEd formate page.pdf', 'BHARTI.jpeg', 'BHOLA12.jpeg', 'Birth Certificate (2).pdf', 'Birth certificate(1).pdf', 'Birth certificate.pdf', 'Birth certificate_compressed.pdf', 'board (1).pdf', 'BOARD.pdf', 'Boardcertificate.pdf.pdf', 'Boardcertification.pdf', 'board_certificate (1).pdf', 'board_certificate.pdf', 'bpharmcy result123.pdf', 'BSC ROHIT.jpeg', 'BSc_sem_I II_CBCS old smk (1).pdf', 'BSc_sem_I II_CBCS old smk.pdf', 'Calculator.py', 'Canva Setup 1.111.0.exe', 'Canva Setup 1.93.1.exe', 'Canva Setup 1.94.0.exe', 'CAP3RD  ALOTMAINT LATTER(2).pdf', 'Caste certificate(1).pdf', 'Caste certificate.pdf', 'caste_certificate (1).pdf', 'caste_certificate (2).pdf', 'caste_certificate.pdf', 'cast_certificate.pdf', 'CDP NOTEBOOK.pdf', 'Certificate in Introduction to Collecting and Reporting Adverse Events in Clinical Research.pdf', 'Certificate in pharmacovigilnace and clinical research (1).pdf', 'certificate.pdf', 'CET_Schedule (1).pdf', 'CET_Schedule (2).pdf', 'CET_Schedule.pdf', 'ChatGPT Image May 9, 2026, 12_28_37 AM.png', 'ChatGPT Image May 9, 2026, 12_52_35 AM.png', 'ChatGPT Image May 9, 2026, 12_56_01 AM.png', 'ChromeSetup.exe', 'churn_pretiction.csv', 'Clinical_Trial_Analytics.ipynb', 'Clinical_trial_cleaned.csv', 'clinical_trial_data', 'ConfirmationPage-26100844701 (1).pdf', 'ConfirmationPage-26100844701.pdf', 'ConfirmationPage-26101732534.pdf', 'ConfirmationPage-261610011136.pdf', 'CRPF.pdf MONU.pdf', 'ctg-studies.csv', 'CV sagar .pdf', 'D0004_1734513555.pdf', 'D0004_251610035451_1749397796_1240.pdf', 'DA0A3600', 'daikibo-telemetry-data.json', 'dashboard (2).png', 'dashboard.png', 'Dashboard_Project.pbix', 'DBT SMK 2526 NEW.pdf', 'Degree Certificate.pdf', 'Deloitte - Data Analytics.pdf', 'Desktop', 'Desktop - Copy', 'desktop.ini', 'details (1).pdf', 'details (2).pdf', 'details.pdf', 'Doc12 sagar .docx', 'DocScanner Jan 2, 2025 14-45 (1).pdf', 'Document (1) (1).PDF', 'document (1).pdf', 'document (2).pdf', 'document.pdf', 'Documents-List.png', 'Domicile certificate(1).pdf', 'Domicile certificate.pdf', 'Domicile certificate_compressed.pdf', 'DOMOCIALAMK.pdf', 'download', 'download (1)', 'download (1).pdf', 'download (2). ssc', 'download (2)..pdf', 'download.pdf', 'downloadsmk msc', 'drug-event-0001-of-0005.json.zip', 'E Call Letter.pdf', 'EAadhaar_2821410400066120211008161813_26102024225748.pdf', 'EAadhaar_2821410400066120211008161813_29122024142839.pdf', 'EAadhaar_2821410400066120211008161813_29122024143333.pdf', 'fda_adverse_events_2015_2026_CLEAN.csv', 'File_202252812135243.webp', 'Final Year Marksheet(1).pdf', 'Final Year Marksheet.pdf', 'firstprogram.py', 'G1.jpeg', 'G12.jpeg', 'G13.jpeg', 'ganapti photo', 'gcapi.dll', 'ghatnapati ak logo.jpg', 'ghatnapati_ak_logo-removebg-preview.png', 'healthcare_dataset.csv', 'HSC board certi', 'HSC board certi (1)', 'HSC board certi.pdf', 'HSC ROHIT.jpeg', 'ID proof(1).pdf', 'ID proof.pdf', 'Identity Slip pdf.pdf', 'images-Photoroom.png', 'images.webp', 'IMG20241218122145 (1).jpg', 'IMG20241218122145.jpg', 'IMG_20250216_131054.jpg', 'IMG_20250216_131055.jpg', 'IMG_20250216_131056.jpg', 'IMG_20250216_131057 (1).jpg', 'IMG_20250216_131057 (2).jpg', 'IMG_20250216_131057.jpg', 'Indian_Army_DG_EME_Group_C_Bharti_2025_Form.pdf', 'INDIVIDUAL CASE SAFETY REPORT.docx', 'INFORMATION M J KHANDALE.pdf', 'installnp.exe', 'intership photo smk 008 12 .pdf', 'J-09-14-II.pdf', 'J-47-14-II.pdf', 'JIJAU KHANDALE (1).docx', 'Jijau Khandale Resume.docx', 'Jijau Khandale Resume.pdf', 'Jijau Khandale Resume.pdf.docx', 'JIJAU KHANDALE.docx', 'Jijau Khandale.pdf', 'JIJAU MOHAN KHANDALE RESUME.docx', 'JIJAU MOHAN KHANDALE.docx', 'JIJAU.docx', 'Jijau_Khandale_ClinicalSafetyCoordinator_Resume.docx', 'Jijau_Khandale_CoverLetter_ClinicalSafetyCoordinator.docx', 'Jijau_Khandale_DataAnalyst_Resume.docx', 'Jijau_Khandale_DataProcessingAnalyst_Numerator_v2.docx', 'Jijau_Khandale_Data_Analyst_Resume.pdf (1).docx', 'Jijau_Khandale_Data_Analyst_Resume.pdf.docx', 'Jijau_Khandale_InfosysBPM_1Page.docx', 'Jijau_Khandale_IQVIA_Analyst.docx', 'Jijau_Khandale_Labcorp_DMC_Resume.docx', 'Jijau_Khandale_MIS_Executive_ATS_Resume.docx', 'Jijau_Khandale_Numerator.docx', 'Jijau_Khandale_Pharmacovigilance_Resume.docx', 'Jijau_Khandale_PowerBI_Engineer.docx', 'Jijau_Khandale_PowerBI_Engineer.pdf', 'Jijau_Khandale_PowerBI_Engineer_v3.docx', 'Jijau_Khandale_QualityAssociate_Amazon.docx', 'Jijau_Khandale_QualityAssociate_Amazon.pdf', 'Jijau_Khandale_QualityAssociate_Amazon_v2.docx', 'Jijau_Khandale_Resume_CRISIL.docx', 'Jijau_Mohan_Khandale_PV_Resume.docx', 'Jijau_Mohan_Khandale_Resume.docx', 'kasing.jpeg', 'khot vahini_enhanced.jpg', 'LAST DBT FORM.pdf', 'Leaving Certificate(1).pdf', 'Leaving Certificate.pdf', 'Leaving Certificate_compressed.pdf', 'm12.jpeg', 'm34.jpeg', 'Maharashtra_DV_List1.pdf', 'Maharashtra_DV_List2.pdf', 'Marathi_Preamble_to_the_Constitution_of_India.jpg', 'Microsoft.Management.Deployment.winmd', 'MONU PHOTO_processed (1).jpeg', 'MONU PHOTO_processed.jpeg', 'monu signature.jpeg', 'monu.jpg', 'monu1.jpg', 'monu10thSSC.jpeg', 'monu12thhsc.jpeg', 'MONUcast.jpeg', 'monuTC.jpeg', 'msc 2nd result.pdf', 'msc 2nd result_compressed.pdf', 'mysql-9.6.0-winx64.msi', 'mysql-connector-net-9.6.0 (1).msi', 'mysql-connector-net-9.6.0.msi', 'mysql-installer-web-community-8.0.42.0.msi', 'mysql-installer-web-community-8.0.45.0 (1).msi', 'mysql-installer-web-community-8.0.45.0.msi', 'Nail_It_5_2048x2048.webp', 'Narrative.docx', 'new BEd fomate practical 1st paper M  Sir  न्यू 1.pdf', 'new BEd fomate practical 1st paper M  Sir  न्यू 1234455.pdf', 'new BEd fomate practical 1st paper M  Sir.docx', 'new BEd fomate practical 1st paper M  Sir.pdf', 'New Doc 03-04-2026 18.41.pdf', 'New Doc 10-19-2025 22.11.pdf', 'New Labharthi Nivad Samiti.pdf', 'new logo photo.pdf', 'new smk 25-26 dbt.pdf', 'new.jpeg', 'NEWFILEPHOTO3.jpeg', 'OBSERVATINAL STUDt.pptx', 'Order_items_Table.csv', 'Order_Table.csv', 'Order_Table1.csv', 'OTR-10009348574.pdf', 'OTR-10014576278.pdf', 'P0023182021MARCHCert (1).pdf', 'P0023182021MARCHCert.pdf', 'P0023182021MARCHMarksheet.pdf', 'Panel Discussion 2024-25-PPT (1).pdf', 'Panel Discussion 2024-25-PPT (2).pdf', 'Panel Discussion 2024-25-PPT.pdf', 'Panel Discussion)“भारतीय संविधान आणि शिक्षण”.pdf', 'path niyojan.pdf', 'Pattern Wallpaper.jpeg', 'PBIDesktopSetup_x64.exe', 'pdf.pdf', 'Pharmacovigilance_Safety_Analysis_Project_Presentation.pptx', 'photo smk epc 2nd.pdf', 'photo-1541701494587-cb58502866ab.avif', 'photo-1559666126-84f389727b9a.avif', 'Photo.jpg', 'photo_with_name.jpg', 'Pi7_Passport_Photo.jpeg', 'Pi7_Tool_AMKPHOTO30.jpg', 'Pi7_Tool_aniket cast  (2) (1).pdf', 'Pi7_Tool_aniket cast  (2).pdf', 'Pi7_Tool_msc 2nd result_compressed.pdf', 'Pi7_Tool_sagar 10th.pdf', 'Pi7_Tool_sagar 12th.pdf', 'Pi7_Tool_sagar cast_converted.pdf', 'Pi7_Tool_sagar degrre bsc (1)_repaired (1).pdf', 'Pi7_Tool_sagar domocile.pdf', 'Pi7_Tool_sagar sign 2.jpg', 'Pi7_Tool_sagar2.jpg', 'Pi7_Tool_SMK ADHARCARD (1).pdf', 'Pi7_Tool_smk boardcertificate 10ths td.pdf', 'Picsart AI Photo Editor Installer.exe', 'picwish-setup (1).exe', 'picwish-setup.exe', 'pizza_sales (1).zip', 'pizza_sales.zip', 'POLICE 2024 SAGAR पोलीस.pdf', 'pops pdf 123.docx', 'presentation ppt TATA Gen AI (1).pptx', 'presentation ppt TATA Gen AI.pptx', 'Presentation1 pops 123 new.pdf', 'Product_Table.csv', 'Professional_PV_Project_Presentation.pptx', 'Proof of Age.pdf', 'Proof of Category (1).pdf', 'Proof of Category (2).pdf', 'Proof of Category.pdf', 'Proof of Domicile (1).pdf', 'Proof of Domicile (2).pdf', 'Proof of Domicile (3).pdf', 'Proof of Domicile.pdf', 'Proof of Educational Qualification.pdf', 'Proof of Knowledge of Marathi Language .pdf', 'Provisional certificate(2).pdf', 'Provisional certificate.pdf', 'pv concept.pdf', 'pv project.docx', 'PV_Project_Presentation.pptx', 'python-3.14.0-amd64 (1).exe', 'python-3.14.0-amd64 (2).exe', 'python-3.14.0-amd64.exe', 'Q72507497128.pdf', 'Q82407164905.pdf', 'Q82409517097.pdf', 'Q82409809388.pdf', 'Q82414619132.pdf', 'Q82417458091.pdf', 'Q82417699381.pdf', 'RA course technobridge at pun.html', 'RA course technobridge at pun_files', 'Reader_Install_Setup.exe', 'README (1).md', 'README (2).md', 'README (3).md', 'README (4).md', 'README.md', 'Receipt_Details_4533823 (1).html', 'Receipt_Details_4533823.html', 'Receipt_Details_4864713.html', 'Recruitment for the Post of Assistant -  AMK ADMITCARD.pdf', 'renamed-images_zip.zip', 'RESULT MSC 2ND 123.jpeg', 'RESULT MSC 2ND.jpeg', 'RESULT MSC 2ND.jpeg 123.jpeg', 'Resume chronological.docx', 'resume CPT coding (1) (1).docx', 'resume CPT coding (1) (2).docx', 'resume CPT coding (1).docx', 'resume CPT coding.docx', 'ROHIT ADDMISION  2ND.jpeg', 'ROHIT.pdf', 'ROHIT2ND MSC.jpeg', 'ROHIT2ND.mhtml', 'ROHITPHOTO.jpeg', 'ROHITSIGN.jpeg', 'ROHITSIGN1.jpeg', 'ROHITSIGN2.jpeg', 'rptGaneshFestivalForm (1) (1).pdf', 'rptGaneshFestivalForm (1) (2).pdf', 'rptGaneshFestivalForm (1).pdf', 'rptGaneshFestivalForm (2).pdf', 'rptGaneshFestivalForm.pdf', 'sagar 10th.pdf', 'sagar 12th.pdf', 'sagar bharti signature.jpg', 'sagar bharti.jpg', 'sagar cast (1).pdf', 'sagar cast (10).pdf', 'sagar cast (2).pdf', 'sagar cast (3).pdf', 'sagar cast (4).pdf', 'sagar cast (5).pdf', 'sagar cast (6).pdf', 'sagar cast (7).pdf', 'sagar cast (8).pdf', 'sagar cast (9).pdf', 'sagar cast 2 (1).pdf', 'sagar cast 2.pdf', 'sagar cast.pdf', 'sagar cast_compressed.pdf', 'sagar cast_converted.pdf', 'sagar degrre bsc (1).pdf', 'sagar degrre bsc (2).pdf', 'sagar degrre bsc.pdf', 'sagar domocile.pdf', 'sagar domocile_compressed.pdf', 'sagar resume 12 (1).docx', 'sagar resume 12.docx', 'sagar resume 123.pdf', 'sagar sign 2.jpg', 'sagar sign.png', 'sagar validity.pdf', 'sagar-18k.jpg', 'Sagarcastcertificate.pdf', 'sagarmk25.jpg', 'sagarsign12 (1).jpeg', 'sagarsign12.jpeg', 'sagarsign13 (1).jpg', 'sagarsign13.jpg', 'sagarsign4 - Edited 25.jpg', 'sagarSSCcertificate.pdf', 'Sales performance dashboard.pbix', 'Sales_dataset.csv', 'Sales_dataset.xlsx', 'Sample - Superstore.csv', 'Sample Dispatch for -After 15 to 30 Sep Joines (1) (3).xlsx', 'Sample Dispatch for -After 15 to 30 Sep Joines (1).xlsx', 'scientist maths and science nots S008.pdf', 'sc_st_proof.pdf', 'SET QP', 'shivraj (1).jpeg', 'shivraj (1).jpg', 'shivraj ssc aplication form (1).pdf', 'shivraj ssc aplication form (2).pdf', 'shivraj ssc aplication form (3).pdf', 'shivraj ssc aplication form.pdf', 'shivraj.jpeg', 'SIGN.jpeg', 'sign123.jpg', 'signature (2).jpeg', 'SIGNATURE-Photoroom.jpg', 'SIGNATURE-Photoroom.png', 'signature.jpeg', 'signature.jpg', 'sk.jpeg', 'skcastpdf.pdf', 'smk activity BEd1st.jpg', 'SMK ADHARCARD (1).pdf', 'SMK ADHARCARD.jpeg', 'SMK ADHARCARD.pdf', 'smk birthcerftificat.pdf', 'smk boardcertificate 10ths td.pdf', 'SMK CAST CERT PDF.pdf', 'smk practical  mate sir.pdf', 'smk008 tutorial.pdf', 'smk25.jpg', 'smkadmison recipte.jpeg', 'smkcast.pdf', 'smkcastpdf (1).pdf', 'SMKCASTPDF.pdf', 'SOLAPUR_Vacancy_List.xlsx', 'Solar smk 008 1neww.pdf', 'sql project code result file.docx', 'SQL_Project', 'ssc board (1).pdf', 'ssc board (1)_compressed.pdf', 'ssc board.pdf', 'SSC Certificate(1).pdf', 'SSC Certificate.pdf', 'SSC ROHIT.jpeg', 'SSCAMKBOARD (1).pdf', 'SSCAMKBOARD.pdf', 'student_user_login (1).pdf', 'student_user_login.pdf', 'Superstore Dashboards..pdf', 'Superstore Dataset (1).xlsx', 'superstore dataset.xlsx', 'Superstore_Dashboard.pdf', 'Superstore_Dashboard.pdf.xlsx', 'synthetic_drug_data (1).csv', 'TableauPublicDesktop-64bit-2025-2-0.exe', 'Task 5 Equality Table.xlsx', 'TATA GenAI Data Analytic.pdf', 'TATA Visualization Project.pbix', 'Telco-Customer-Churn.csv', 'Telco-Customer-Churn.csv.xlsx', 'time tabel (1).pdf', 'time tabel.pdf', 'turquoise-gradient-color-fabric-texture-carpet-background-free-photo.jpg', 'Two wheeler driving licence.pdf', 'UCG-NET-240520053668-1732472568.pdf', 'UCG-NET-240520053668-1734509424.pdf', 'UltraViewer_setup_6.6_en.exe', 'Undertaking form.pdf', 'Undertaking_self  declaration 11th (1).pdf', 'Undertaking_self  declaration 11th (2).pdf', 'Undertaking_self  declaration 11th (3).pdf', 'Undertaking_self  declaration 11th.docx', 'Undertaking_self  declaration 11th.pdf', 'Undertaking_self  declaration.pdf', 'unnamed.png', 'Untitled design new 4.pdf', 'uperstore dataset.xlsx', 'upsc.pdf', 'v12.jpeg', 'v13.jpeg', 'VA Allocation & lBL allocation (1).xlsx', 'Vacancies.xls', 'VSCodeUserSetup-x64-1.106.2.exe', 'Walmart Sales Data.csv.csv', 'walmart_sales.csv', 'WA_Fn-UseC_-Telco-Customer-Churn.csv.xlsx', 'WhatsApp Business.html', 'WhatsApp Business.htmlsmk 008.html', 'WhatsApp Business.htmlsmk 008_files', 'WhatsApp Business.mhtml', 'WhatsApp Business_files', 'WhatsApp Image 2024-04-13 at 12.56.53 PM.jpeg', 'WhatsApp Image 2024-04-14 at 3,31,37 PM - Copy_enhanced.jpeg', 'WhatsApp Image 2024-04-14 at 3.31.37 PM.jpeg', 'WhatsApp Image 2024-07-20 at 5.13.18 PM.jpeg', 'WhatsApp Image 2024-07-27 at 8.17.11 PM.jpeg', 'WhatsApp Image 2024-08-06 at 11.02.02 PM.jpeg', 'WhatsApp Image 2024-08-21 at 12,54,45 PM_processed.jpeg', 'WhatsApp Image 2024-08-21 at 12.52.07 PM (1).jpeg', 'WhatsApp Image 2024-08-21 at 12.52.07 PM.jpeg', 'WhatsApp Image 2024-08-21 at 12.52.10 PM.jpeg', 'WhatsApp Image 2024-08-21 at 12.52.11 PM.jpeg', 'WhatsApp Image 2024-08-21 at 12.52.14 PM.jpeg', 'WhatsApp Image 2024-08-21 at 12.54.45 PM.jpeg', 'WhatsApp Image 2024-08-21 at 12.54.49 PM.jpeg', 'WhatsApp Image 2024-08-21 at 12.54.51 PM.jpeg', 'WhatsApp Image 2024-08-21 at 12.54.52 PM.jpeg', 'WhatsApp Image 2024-08-29 at 1.16.34 PM.jpeg', 'WhatsApp Image 2024-08-29 at 1.16.35 PM.jpeg', 'WhatsApp Image 2024-08-29 at 1.16.36 PM (1).jpeg', 'WhatsApp Image 2024-08-29 at 1.16.36 PM.jpeg', 'WhatsApp Image 2024-09-23 at 7.46.06 PM.jpeg', 'WhatsApp Image 2024-09-23 at 7.46.06 PM.pdf', 'WhatsApp Image 2024-09-23 at 9.24.33 PM.jpeg', 'WhatsApp Image 2024-09-23 at 9.24.33 PM.pdf', 'WhatsApp Image 2024-09-23 at 9.24.34 PM.jpeg', 'WhatsApp Image 2024-09-23 at 9.24.34 PM.pdf', 'WhatsApp Image 2024-09-23 at 9.54.59 PM.jpeg', 'WhatsApp Image 2024-09-23 at 9.54.59 PM.pdf', 'WhatsApp Image 2024-10-01 at 7.49.55 PM.jpeg', 'WhatsApp Image 2024-10-26 at 10_converted.pdf', 'WhatsApp Image 2024-10-26 at 9.54.48 PM.jpg', 'WhatsApp Image 2024-12-21 at 10.53.42 PM.jpeg', 'WhatsApp Image 2024-12-21 at 10.53.43 PM.jpeg', 'WhatsApp Image 2024-12-21 at 10.56.48 PM (1).jpeg', 'WhatsApp Image 2024-12-21 at 10.56.48 PM.jpeg', 'WhatsApp Image 2024-12-21 at 11.01.18 PM.jpeg', 'WhatsApp Image 2024-12-21 at 11.03.14 PM.jpeg', 'WhatsApp Image 2024-12-29 at 2.36.15 PM.jpeg', 'WhatsApp Image 2025-01-18 at 11.41.34 AM.jpeg', 'WhatsApp Image 2025-02-16 at 7.37.37 PM (1).jpeg', 'WhatsApp Image 2025-02-16 at 7.37.37 PM.jpeg', 'WhatsApp Image 2025-02-20 at 1.37.08 PM.jpeg', 'WhatsApp Image 2025-02-20 at 1.37.08 PM_compressed.pdf', 'WhatsApp Image 2025-02-20 at 1.54.37 PM.jpeg', 'WhatsApp Image 2025-02-20 at 11.03.49 AM.pdf', 'WhatsApp Image 2025-02-20 at 8.07.48 PM.jpeg', 'WhatsApp Image 2025-02-20 at 8.32.34 PM.jpeg', 'WhatsApp Image 2025-02-28 at 10,53,49 PM_enhanced (1).jpeg', 'WhatsApp Image 2025-02-28 at 10,53,49 PM_enhanced.jpeg', 'WhatsApp Image 2025-02-28 at 10.50.24 PM (1).jpeg', 'WhatsApp Image 2025-02-28 at 10.50.24 PM.jpeg', 'WhatsApp Image 2025-02-28 at 10.53.49 PM.jpeg', 'WhatsApp Image 2025-02-28 at 10.53.50 PM.jpeg', 'WhatsApp Image 2025-06-01 at 11.41.52 PM.jpeg', 'WhatsApp Image 2025-06-01 at 11.46.56 PM (1).jpeg', 'WhatsApp Image 2025-06-01 at 11.54.31 PM.jpeg', 'WhatsApp Image 2025-06-02 at 6.07.03 PM.jpeg', 'WhatsApp Image 2025-06-02 at 6.07.12 PM.jpeg', 'WhatsApp Image 2025-06-02 at 6.16.48 PM.jpeg', 'WhatsApp Image 2025-06-02 at 6.19.10 PM.jpeg', 'WhatsApp Image 2025-06-25 at 3.19.55 PM.jpeg', 'WhatsApp Image 2025-06-30 at 15.17.13.jpeg', 'WhatsApp Image 2025-06-30 at 15.31.35.jpeg', 'WhatsApp Image 2025-07-04 at 18.40.21.jpeg', 'WhatsApp Image 2025-08-11 at 11.17.14 PM (1).jpeg', 'WhatsApp Image 2025-08-11 at 11.17.14 PM.jpeg', 'WhatsApp Image 2025-08-11 at 11.17.15 PM (1).jpeg', 'WhatsApp Image 2025-08-11 at 11.17.15 PM (2).jpeg', 'WhatsApp Image 2025-08-11 at 11.17.15 PM.jpeg', 'WhatsApp Image 2025-08-11 at 11.17.16 PM (1).jpeg', 'WhatsApp Image 2025-08-11 at 11.17.16 PM (2).jpeg', 'WhatsApp Image 2025-08-11 at 11.17.16 PM (3).jpeg', 'WhatsApp Image 2025-08-11 at 11.17.16 PM.jpeg', 'WhatsApp Image 2025-08-11 at 11.17.17 PM (1).jpeg', 'WhatsApp Image 2025-08-11 at 11.17.17 PM (2).jpeg', 'WhatsApp Image 2025-08-11 at 11.17.17 PM.jpeg', 'WhatsApp Image 2025-08-11 at 11.17.18 PM (1).jpeg', 'WhatsApp Image 2025-08-11 at 11.17.18 PM.jpeg', 'WhatsApp Image 2025-08-11 at 11.17.19 PM.jpeg', 'WhatsApp Image 2025-08-12 at 12.31.53 AM.jpeg', 'WhatsApp Image 2025-08-12 at 12.37.37 AM.jpeg', 'WhatsApp Image 2025-08-18 at 4.28.03 PM.jpeg', 'WhatsApp Image 2025-08-18 at 7.03.23 PM (1).jpeg', 'WhatsApp Image 2025-08-18 at 7.03.23 PM (2).jpeg', 'WhatsApp Image 2025-08-18 at 7.03.23 PM.jpeg', 'WhatsApp Image 2025-08-18 at 7.03.24 PM (1).jpeg', 'WhatsApp Image 2025-08-18 at 7.03.24 PM.jpeg', 'WhatsApp Image 2025-08-18 at 7.07.18 PM.jpeg', 'WhatsApp Image 2025-09-25 at 10.43.39 PM.jpeg', 'WhatsApp Image 2025-09-25 at 11.08.44 PM.jpeg', 'WhatsApp Image 2025-09-25 at 11.09.41 PM.jpeg', 'WhatsApp Image 2025-09-25 at 11.28.10 PM.jpeg', 'WhatsApp Image 2025-09-26 at 12.17.38 AM.jpeg', 'WhatsApp Image 2025-09-26 at 3.24.52 PM.jpeg', 'WhatsApp Image 2025-10-19 at 9.16.23 PM.jpeg', 'WhatsApp Image 2025-10-23 at 10.05.34 PM.jpeg', 'WhatsApp Image 2025-10-23 at 8.56.16 PM.jpeg', 'WhatsApp 

In [3]:
'Clinical_trial_cleaned.csv' in os.listdir()

True

In [6]:
import pandas as pd

df = pd.read_csv(r"C:\Users\hp\Downloads\clinical_trial_data\Clinical_trial_cleaned.csv")

In [7]:
df.shape

(500, 23)